export const createDefaultState = () => ({
  extensionVersion: "0.7.5",
  busy: false,
  uiMode: "expanded",
  operationState: "loading",
  lifecyclePhase: "idle",
  progress: { phase: "idle", phaseProgress: 0, overallProgress: 0, value: 0 },
  lastResult: null,
  seed: "",
  capabilities: {},
  conflicts: [],
  compatibility: {},
  lifecycle: {},
  transaction: null,
  locks: { summary: {}, categories: {}, vehicle: false, configuration: false },
  index: { models: 0, configurations: 0, blacklists: {}, sources: {} },
  garage: {
    entries: [], total: 0, page: 0, pageCount: 1, pendingSave: false,
    storage: {}, query: {}, preflight: null, details: null, comparison: null,
  },
  history: [],
  lineup: { current: null, stored: 0 },
  spawnDirector: { managed: [], run: null, placement: {}, preview: null },
  aiDirector: { capabilities: {}, vehicles: [], destination: { status: "empty" }, route: { points: [] } },
  performance: {},
  migration: {},
  settings: {
    schemaVersion: 9,
    chaos: 75,
    allowMissingParts: true,
    protectCriticalParts: false,
    contentFilter: "everything",
    includeAutomation: false,
    includeTrailers: false,
    includeProps: false,
    selectionFairness: "vehicle",
    historyLimit: 10,
    diagnosticLogging: false,
    performanceProfiling: false,
    performanceBudgets: {
      idleBudgetMs: 0.5, busyBudgetMs: 2.5, raceBudgetMs: 3.5,
      uiPublishBudgetMs: 1.5, indexChunkBudgetMs: 2,
    },
    manualSeed: "",
    seedMode: "random",
    rememberLocks: false,
    dnaLibraryLimit: 100,
    autoSaveDNA: false,
    defaultRestoreMode: "exact",
    extremeTuning: false,
    allowPartialResult: false,
    uiPreferences: { schemaVersion: 2, localeMode: "auto", manualLocale: "en-US", race: {}, legacyRacePolicyImported: false },
  },
})
