<template><section><div class="scr-card scr-form-grid"><NumericInput :model-value="Number(options.count || 4)" :label="t('race.totalVehicles')" :min="1" :max="32" @update:model-value="value => update('count', value)" /><label class="scr-field"><span>{{ t('race.participation') }}</span><select :value="options.participationMode || 'spectator'" @change="update('participationMode', $event.target.value)"><option value="player">{{ t('race.player') }}</option><option value="spectator">{{ t('race.spectator') }}</option></select></label><label class="scr-field"><span>{{ t('race.episodeSeed') }}</span><input :value="options.episodeSeed || ''" maxlength="128" @change="update('episodeSeed', $event.target.value)" /></label><label class="scr-field"><span>{{ t('race.preset') }}</span><select :value="options.preset || 'Balanced'" @change="preset($event.target.value)"><option v-for="value in presets" :key="value" :value="value">{{ t(`race.presetValue.${value}`) }}</option></select></label></div><RacePolicyPanel :open="false" /><div class="scr-actions"><button v-if="!current?.active && !core.busy" type="button" class="is-hot" :disabled="conflict" @click="generate">{{ t('race.generate') }}</button><button v-else type="button" @click="stores.command.send('cancelRaceGeneration')">{{ t('race.cancelGeneration') }}</button><button type="button" @click="stores.command.send('exportChaosLineup')">{{ t('common.export') }}</button><button type="button" @click="stores.command.send('importChaosLineup')">{{ t('common.import') }}</button></div><CompetitorList /></section></template>
<script setup>
import { computed } from "vue"; import { useStores } from "../../stores"; import NumericInput from "../common/NumericInput.vue"; import RacePolicyPanel from "./RacePolicyPanel.vue"; import CompetitorList from "./CompetitorList.vue"
const stores = useStores(); const core = stores.core.state; const options = stores.race.state.options; const { t } = stores.i18n; const current = computed(() => stores.race.state.lineup?.current); const conflict = computed(() => !options.allowOfficialVehicles && !options.allowModVehicles); const presets = ["Balanced", "Maximum Chaos", "Mods Showcase", "Custom"]
const balancedPolicy = Object.freeze({ acceptPartial: false, acceptMetadataUncertain: false, acceptPotentiallyUndrivable: false, avoidDuplicateModels: true, avoidDuplicateConfigurations: true, avoidDuplicateFamilies: false, maximumSameFamily: 2, diversifyVehicleClasses: true, diversifyPropulsion: false, diversifyDrivetrain: false, diversifySource: true, diversifyWheelStyles: false, diversifyBodyTypes: false, allowOfficialVehicles: true, allowModVehicles: true, allowAutomationVehicles: false, allowTrailers: false, allowProps: false, maxAttemptsPerCompetitor: 3, maxConsecutiveFailures: 4, retainAcceptedOnCancel: true })
const presetValues = { "Balanced": { ...balancedPolicy }, "Maximum Chaos": { ...balancedPolicy, acceptPartial: true, acceptMetadataUncertain: true, acceptPotentiallyUndrivable: true }, "Mods Showcase": { ...balancedPolicy, acceptMetadataUncertain: true, allowOfficialVehicles: false, allowModVehicles: true } }
function update(field, value) { options[field] = value; if (field !== "preset") options.preset = "Custom"; stores.command.send("updateUIPreferences", [{ race: { [field]: value, ...(field !== "preset" ? { preset: "Custom" } : {}) } }]) }
function preset(value) { Object.assign(options, presetValues[value] || {}, { preset: value }); stores.command.send("updateUIPreferences", [{ race: { ...options } }]) }
function generate() { stores.command.send("createChaosLineup", [{ ...options }]) }
</script>
