<template><section class="scr-panel" aria-labelledby="scr-garage-title"><h2 id="scr-garage-title" class="scr-sr-only">{{ t('nav.garage') }}</h2><SegmentedControl v-model="layout.garageSection" :label="t('nav.garage')" :items="sections" /><form class="scr-save-row" @submit.prevent="save"><input v-model="dnaName" :placeholder="t('garage.name')" maxlength="128" /><button type="submit" :disabled="core.busy">{{ t('garage.saveDNA') }}</button></form><template v-if="layout.garageSection === 'saved'"><GarageToolbar /><LoadingState v-if="garage.loaded === false && garage.loadStatus !== 'failed'" :message="t('garage.loading')" /><ErrorState v-else-if="garage.loadStatus === 'failed'" :message="garage.loadStatus" /><EmptyState v-else-if="!(garage.entries || []).length" :message="t('garage.empty')" /><component v-else :is="layout.garageView === 'list' ? GarageList : GarageGrid" :entries="garage.entries" :selected-id="garage.selectedId" :busy="core.busy" @select="select" @restore="entry => restore(entry, 'exact')" @replay="entry => stores.command.send('replayVehicleDNAGeneration', [entry.id, 'original'])" @favorite="entry => stores.command.send('setVehicleDNAFavorite', [entry.id, entry.favorite !== true])" /><footer class="scr-pagination"><button type="button" :disabled="garage.page <= 0" @click="page(-1)">{{ t('common.previous') }}</button><span>{{ t('garage.page', { page: (garage.page || 0) + 1, pages: garage.pageCount || 1 }) }}</span><button type="button" :disabled="garage.page >= (garage.pageCount || 1) - 1" @click="page(1)">{{ t('common.next') }}</button></footer></template><VehicleDNACompare v-else-if="layout.garageSection === 'compare'" /><VehicleDNAImportExport v-else /><VehicleDNADetails @close="garage.details = null" /></section></template>
<script setup>
import { ref } from "vue"; import { useStores } from "../../stores"; import { confirmDialog } from "../../services/dialogs"; import SegmentedControl from "../common/SegmentedControl.vue"; import LoadingState from "../common/LoadingState.vue"; import ErrorState from "../common/ErrorState.vue"; import EmptyState from "../common/EmptyState.vue"; import GarageToolbar from "./GarageToolbar.vue"; import GarageGrid from "./GarageGrid.vue"; import GarageList from "./GarageList.vue"; import VehicleDNADetails from "./VehicleDNADetails.vue"; import VehicleDNACompare from "./VehicleDNACompare.vue"; import VehicleDNAImportExport from "./VehicleDNAImportExport.vue"
const stores = useStores(); const core = stores.core.state; const garage = stores.garage.state; const layout = stores.uiLayout.state; const { t } = stores.i18n; const dnaName = ref(""); const sections = [{ value: "saved", label: t("garage.saved") }, { value: "compare", label: t("garage.compare") }, { value: "share", label: t("garage.share") }]
function save() { stores.command.send("saveVehicleDNA", [dnaName.value || "Vehicle DNA"]); dnaName.value = "" }
function select(entry) { garage.selectedId = entry.id; stores.command.send("getVehicleDNADetails", [entry.id]) }
async function restore(entry, mode) { await stores.command.send("preflightVehicleDNA", [entry.id, mode]); const label = t(mode === "exact" ? "garage.restoreExact" : "garage.restoreCompatible"); const ok = await confirmDialog(layout, label, t("garage.restoreConfirm", { mode: label, name: entry.name })); if (ok) stores.command.send("restoreVehicleDNA", [entry.id, mode, mode === "compatible"]) }
function page(delta) { stores.command.send("setVehicleDNAPage", [Math.max(0, Number(garage.page || 0) + delta)]) }
</script>
