<template><DetailsPanel :open="!!entry" :title="entry ? vehicleDisplayName(entry, t) : t('common.details')" @close="$emit('close')"><template v-if="entry"><ThumbnailViewer :entry="entry" /><div class="scr-tech-grid"><span><code>id</code>: {{ entry.id }}</span><span><code>modelKey</code>: {{ entry.modelKey || entry.final?.modelKey }}</span><span><code>seed</code>: {{ entry.generation?.seed || entry.seed }}</span><span><code>lineage depth</code>: {{ entry.lineage?.generation || 0 }}</span><span><code>generatorVersion</code>: {{ entry.generatorVersion || entry.generation?.generatorVersion }}</span></div><div class="scr-actions"><button type="button" :disabled="busy" @click="restore('exact')">{{ t('garage.restoreExact') }}</button><button type="button" :disabled="busy" @click="restore('compatible')">{{ t('garage.restoreCompatible') }}</button><button type="button" :disabled="busy" @click="stores.command.send('replayVehicleDNAGeneration', [entry.id, 'original'])">{{ t('garage.replay') }}</button><button type="button" :disabled="busy" @click="pureSeed">{{ t('garage.pureSeed') }}</button><button type="button" :disabled="busy" @click="mutate('small')">{{ t('mutation.small') }}</button><button type="button" :disabled="busy" @click="mutate('medium')">{{ t('mutation.medium') }}</button><button type="button" :disabled="busy" @click="mutate('wild')">{{ t('mutation.wild') }}</button><button type="button" :disabled="busy" @click="stores.command.send('rerollUnlocked', [{ parentDNAId: entry.id }])">{{ t('chaos.rerollUnlocked') }}</button></div><MetadataEditor :entry="entry" /><div class="scr-actions"><button type="button" @click="stores.command.send('setVehicleDNAFavorite', [entry.id, entry.favorite !== true])">{{ t('garage.favorite') }}</button><button type="button" @click="stores.command.send('setVehicleDNAPinned', [entry.id, entry.pinned !== true])">{{ t('garage.pin') }}</button><button type="button" @click="stores.command.send('duplicateVehicleDNA', [entry.id])">{{ t('garage.duplicate') }}</button><button type="button" @click="stores.command.send('captureVehicleDNAThumbnail', [entry.id])">{{ t('garage.thumbnailCapture') }}</button><button type="button" @click="captureNonExact">{{ t('garage.thumbnailNonExact') }}</button><button type="button" @click="stores.command.send('removeVehicleDNAThumbnail', [entry.id])">{{ t('garage.thumbnailRemove') }}</button><button type="button" class="is-danger" @click="remove">{{ t('common.delete') }}</button></div></template></DetailsPanel></template>
<script setup>
import { computed } from "vue"; import { useStores } from "../../stores/index.js"; import { confirmDialog } from "../../services/dialogs.js"; import DetailsPanel from "../common/DetailsPanel.vue"; import ThumbnailViewer from "./ThumbnailViewer.vue"; import MetadataEditor from "./MetadataEditor.vue"
import { vehicleDisplayName } from "../../services/humanLabels.js"
defineEmits(["close"]); const stores = useStores(); const details = computed(() => stores.garage.state.details); const entry = computed(() => details.value?.entry || null); const busy = computed(() => stores.core.state.busy); const { t } = stores.i18n
async function restore(mode) { if (!entry.value) return; await stores.command.send("preflightVehicleDNA", [entry.value.id, mode]); const label = t(mode === "exact" ? "garage.restoreExact" : "garage.restoreCompatible"); const ok = await confirmDialog(stores.uiLayout.state, label, t("garage.restoreConfirm", { mode: label, name: entry.value.name })); if (ok) stores.command.send("restoreVehicleDNA", [entry.value.id, mode, mode === "compatible"]) }
async function pureSeed() { if (await confirmDialog(stores.uiLayout.state, t("garage.pureSeed"), t("garage.pureSeedConfirm"))) stores.command.send("pureSeedReplayVehicleDNA", [entry.value.id]) }
async function captureNonExact() { if (await confirmDialog(stores.uiLayout.state, t("garage.thumbnailNonExact"), t("garage.thumbnailNonExactConfirm"))) stores.command.send("captureVehicleDNAThumbnail", [entry.value.id, { allowNonExact: true }]) }
async function remove() { if (await confirmDialog(stores.uiLayout.state, t("common.delete"), t("garage.deleteConfirm", { name: entry.value.name }))) stores.command.send("deleteVehicleDNA", [entry.value.id]) }
const mutate = strength => stores.command.send("mutateVehicleDNA", [entry.value.id, strength, {}])
</script>
