<template><section class="scr-card"><h3>{{ t('locks.title') }}</h3><div class="scr-actions"><ToggleField :model-value="locks.vehicle === true" :label="t('locks.vehicle')" :disabled="core.busy" @update:model-value="value => send('lockVehicle', [value])" /><ToggleField :model-value="locks.configuration === true" :label="t('locks.configuration')" :disabled="core.busy" @update:model-value="value => send('lockConfiguration', [value])" /></div><div class="scr-chip-grid"><button v-for="category in categories" :key="category" type="button" :aria-pressed="locks.categories?.[category] === true" :class="{ 'is-active': locks.categories?.[category] }" :disabled="core.busy" @click="send('lockCategory', [category, locks.categories?.[category] !== true])">{{ category }}</button></div><div class="scr-actions"><button v-for="preset in presets" :key="preset" type="button" :disabled="core.busy" @click="send('applyLockPreset', [preset.toLowerCase()])">{{ t(`locks.${preset}`) }}</button><button type="button" :disabled="core.busy" @click="send('lockCurrentParts')">{{ t('locks.lockCurrent') }}</button><button type="button" :disabled="core.busy" @click="send('updateLockProfile', [{ vehicle: false, configuration: false, categories: {}, slots: {}, parts: {}, tuning: {}, paints: {} }])">{{ t('locks.unlockAll') }}</button></div><DetailsPanel :open="open" :title="t('locks.title')" @close="open = false"><div v-for="slot in lockData?.slots || []" :key="slot.path" class="scr-lock-row"><code>{{ slot.path }}</code><button type="button" @click="send(slot.locked ? 'unlockSlot' : 'lockSlot', [slot.path])">{{ slot.locked ? t('locks.unlockAll') : t('locks.lockCurrent') }}</button></div></DetailsPanel><button type="button" @click="showDetails">{{ t('common.details') }}</button></section></template>
<script setup>
import { ref } from "vue"; import { useStores } from "../../stores/index.js"; import ToggleField from "../common/ToggleField.vue"; import DetailsPanel from "../common/DetailsPanel.vue"
const stores = useStores(); const core = stores.core.state; const locks = stores.chaos.state.locks; const { t } = stores.i18n; const open = ref(false); const lockData = ref(null)
const categories = ["body", "engine", "transmission", "drivetrain", "suspension", "brakes", "steering", "wheels", "tires", "aero", "interior", "electronics", "accessories", "props", "other", "tuning", "paint"]
const presets = ["everything", "visual", "mechanical", "accessories"]
const send = (command, args = []) => stores.command.send(command, args)
async function showDetails() { lockData.value = (await send("getVehicleDNALocks"))?.result || null; open.value = true }
</script>
