<template>
  <section ref="root" class="scr-app bngApp" :class="[{ 'is-compact': layout.compact, 'is-reduced-motion': layout.reducedMotion }, `scr-width-${widthClass}`]" bng-ui-scope="soturine-chaos-randomizer" v-bng-scoped-nav="{ scopeId: 'soturine-chaos-randomizer', type: 'container', preferAutoFocus: true }" v-bng-on-ui-nav:back="back">
    <AppHeader @toggle-compact="toggleCompact" @settings="selectTab('settings')" />
    <CompatibilityBadge />
    <OperationProgress @cancel="cancel" />
    <template v-if="layout.compact"><section class="scr-compact" :aria-label="t(`nav.${layout.activeTab}`)"><header><strong>{{ t(`nav.${layout.activeTab}`) }}</strong><span v-if="core.busy">{{ percent }}%</span></header><div v-if="layout.activeTab === 'chaos'"><ChaosActions /><button v-if="core.busy" type="button" @click="cancel">{{ t('status.cancelSafe') }}</button></div><div v-else-if="layout.activeTab === 'garage'" class="scr-compact-summary"><strong>{{ currentDNA?.name || t('garage.empty') }}</strong><span>{{ t('garage.savedCount', { count: stores.i18n.formatNumber(entries.length) }) }} · <code>{{ currentDNA?.modelKey || currentDNA?.final?.modelKey || '—' }}</code></span><div class="scr-actions"><button type="button" :disabled="!currentDNA" @click="garageStep(-1)">{{ t('common.previous') }}</button><button type="button" :disabled="!currentDNA || core.busy" @click="stores.command.send('restoreVehicleDNA', [currentDNA.id, 'exact', false])">{{ t('garage.restoreExact') }}</button><button type="button" :disabled="!currentDNA || core.busy" @click="stores.command.send('replayVehicleDNAGeneration', [currentDNA.id, 'original'])">{{ t('garage.replay') }}</button><button type="button" :disabled="!currentDNA" @click="garageStep(1)">{{ t('common.next') }}</button></div></div><div v-else-if="layout.activeTab === 'race'" class="scr-compact-summary"><strong>{{ raceSummary }}</strong><span>{{ t(`race.presetValue.${race.options?.preset || 'Balanced'}`) }} · {{ race.lineup?.current?.generationState || 'idle' }}</span><div class="scr-actions"><button v-if="!race.lineup?.current?.active && !core.busy" type="button" @click="stores.command.send('createChaosLineup', [{ ...race.options }])">{{ t('race.generate') }}</button><button v-else type="button" @click="stores.command.send('cancelRaceGeneration')">{{ t('race.cancelGeneration') }}</button><button type="button" @click="stores.command.send('startManagedAI', [{ ...race.aiOptions }])">{{ t('common.start') }}</button><button type="button" @click="stores.command.send('pauseManagedAI')">{{ t('common.pause') }}</button><button type="button" @click="stores.command.send('stopManagedAI')">{{ t('common.stop') }}</button></div></div><div v-else class="scr-compact-summary"><span>{{ t('settings.seedSummary', { mode: settings.seedMode, content: settings.contentFilter }) }}</span><span>{{ t('status.locks', { count: lockCount }) }} · {{ settings.protectCriticalParts ? t('common.enabled') : t('common.disabled') }}</span><span>{{ settings.performanceProfiling ? t('settings.profiling') : t('common.disabled') }}</span></div></section></template>
    <template v-else><AppNavigation :active="layout.activeTab" @select="selectTab" /><main class="scr-body" bng-nav-scroll><ChaosPanel v-if="layout.activeTab === 'chaos'" /><GaragePanel v-else-if="layout.activeTab === 'garage'" /><RacePanel v-else-if="layout.activeTab === 'race'" /><SettingsPanel v-else /></main><GlobalStatus @details="stores.uiLayout.toggleDetails()" /></template>
    <ConfirmDialog />
  </section>
</template>
<script setup>
import { computed, ref } from "vue"; import { vBngOnUiNav, vBngScopedNav } from "@/common/directives"; import { useStores } from "../../stores"; import { useResponsiveLayout } from "../../composables/useResponsiveLayout"; import { confirmDialog } from "../../services/dialogs"; import AppHeader from "./AppHeader.vue"; import AppNavigation from "./AppNavigation.vue"; import CompatibilityBadge from "./CompatibilityBadge.vue"; import OperationProgress from "./OperationProgress.vue"; import GlobalStatus from "./GlobalStatus.vue"; import ConfirmDialog from "../common/ConfirmDialog.vue"; import ChaosActions from "../chaos/ChaosActions.vue"; import ChaosPanel from "../chaos/ChaosPanel.vue"; import GaragePanel from "../garage/GaragePanel.vue"; import RacePanel from "../race/RacePanel.vue"; import SettingsPanel from "../settings/SettingsPanel.vue"
const stores = useStores(); const core = stores.core.state; const race = stores.race.state; const settings = stores.settings.state; const layout = stores.uiLayout.state; const { t, plural } = stores.i18n; const root = ref(null); const garageIndex = ref(0); useResponsiveLayout(root, stores.uiLayout)
const percent = computed(() => Math.round(Number(core.progress?.value || 0) * 100)); const widthClass = computed(() => layout.width < 320 ? "narrow" : layout.width < 480 ? "medium" : "wide"); const entries = computed(() => stores.garage.state.entries || []); const currentDNA = computed(() => { if (!entries.value.length) return null; garageIndex.value = Math.min(garageIndex.value, entries.value.length - 1); return entries.value[garageIndex.value] }); const raceSummary = computed(() => plural("race.competitors", Number(race.lineup?.current?.totalVehicles || race.options?.count || 0))); const lockCount = computed(() => Number(stores.chaos.state.locks?.summary?.locked || 0))
function selectTab(tab) { stores.uiLayout.setTab(tab) }
function garageStep(delta) { if (entries.value.length) garageIndex.value = (garageIndex.value + delta + entries.value.length) % entries.value.length }
function toggleCompact() { const next = !layout.compact; stores.uiLayout.setCompact(next); stores.command.send("setUICompactMode", [next ? "collapsed" : "expanded"]) }
async function cancel() { if (await confirmDialog(layout, t("status.cancelSafe"), t("status.cancelConfirm"))) stores.command.send("cancelCurrentOperation") }
function back() { if (layout.dialog) return; if (layout.details[layout.activeTab]) stores.uiLayout.toggleDetails(layout.activeTab); else if (layout.activeTab !== "chaos") selectTab("chaos") }
</script>
